1516 2.4 - IHFF/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IHFF.Models
{
    public class HomeViewModel
    {
        public HomeViewModel(
            IEnumerable<Movie> movies, 
            IEnumerable<Special> specials, 
            IEnumerable<Restaurant> restaurants)
        {
            Movies = movies;
            Specials = specials;
            Restaurants = restaurants;
        }

        public IEnumerable<Movie> Movies { get; set; }
        public IEnumerable<Special> Specials { get; set; }
        public IEnumerable<Restaurant> Restaurants { get; set; }
    }
}

1516 2.4 - IHFF/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IHFF.Repositories;
using IHFF.Interfaces;
using IHFF.Models;
using IHFF.Helpers;

namespace IHFF.Controllers
{
    public class HomeController : Controller
    {
        IMovieRepository moviesRepository = new MoviesRepository();
        ISpecialsRepository specialsRepository = new SpecialsRepository();
        IRestaurantRepository restaurantRepository = new RestaurantsRepository();

        private const int MAXELEMENTS = 4;

        public ActionResult Index()
        {
            IEnumerable<Movie> movies = CollectionUtils.GetRandomElements<Movie>(moviesRepository.GetAllUniqueMovies(), MAXELEMENTS);
            IEnumerable<Special> specials = CollectionUtils.GetRandomElements<Special>(specialsRepository.GetAllSpecials(), MAXELEMENTS);
            IEnumerable<Restaurant> restaurants = CollectionUtils.GetRandomElements<Restaurant>(restaurantRepository.GetAllRestaurants(), MAXELEMENTS);

            HomeViewModel hvm = new HomeViewModel(movies, specials, restaurants);
            return View(hvm);
        }
    }
}

1516 2.4 - IHFF/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IHFF.Models;
using IHFF.Repositories;
using IHFF.Interfaces;

namespace IHFF.Controllers
{
    public class MoviesController : Controller
    {
        private IMovieRepository moviesRepository = new MoviesRepository();
        private IWishlistRepository wishlistRepository = new WishlistRepository();
        private IRestaurantRepository restaurantRepository = new RestaurantsRepository();
        private IFoodFilmRepository foodFilmRepository = new FilmFoodRepository();

        public ActionResult Index()
        {
            return View(moviesRepository.GetAllUniqueMovies());
        }

        [HttpPost]
        public ActionResult Index(int EventId, int ticketAmount)
        {
            Wishlist wishlist = Wishlist.Instance;
            Event e = moviesRepository.GetMovieEvent(EventId);
            if (e == null)
            {
                return RedirectToAction(nameof(Index));
                //return "error";
            }
            WishlistItem item = new WishlistItem(e, ticketAmount, wishlist);

            wishlist.AddItemToWishlist(item);
            return RedirectToAction(nameof(WishlistController.Index), "Wishlist");
            //return "success";
        }

        public ActionResult MovieInfo(int Id)
        {
            MovieViewModel model = new MovieViewModel(restaurantRepository.GetFoodFilmRestaurants(), moviesRepository.GetMovie(Id));
            return PartialView("_MovieInfo", model);
            //return PartialView("_MovieInfo", moviesRepository.GetMovie(Id));
        }

        public ActionResult GetMovies(int day)
        {
            if(day < 0)
            {
                return PartialView("_MovieView", moviesRepository.GetAllUniqueMovies());
            }
            return PartialView("_MovieView", moviesRepository.GetMovies(day));
        }

        public ActionResult FoodAndFilm(int restaurantId, int filmId)
        {
            FoodFilmViewModel model = new FoodFilmViewModel(restaurantRepository.GetRestaurant(restaurantId), moviesRepository.GetMovie(filmId));
            return PartialView("_FoodAndFilm", model);
        }

        [HttpPost]
        public ActionResult FoodAndFilm(int EventId, int RestaurantId, TimeSpan RestaurantTime, int ticketAmount)
        {
            Wishlist wishlist = Wishlist.Instance;
            Event e = moviesRepository.GetMovieEvent(EventId);

            Restaurant restaurant = restaurantRepository.GetRestaurant(RestaurantId);
            RestaurantReservation r = restaurantRepository.CreateReservation(restaurant, ticketAmount, RestaurantTime, (int)e.Date.Day);

            FoodFilm foodFilm = new FoodFilm(e, r);

            foodFilmRepository.AddFoodFilm(foodFilm);

            WishlistItem item = new WishlistItem(foodFilm, wishlist);

            wishlist.AddItemToWishlist(item);
            return RedirectToAction(nameof(WishlistController.Index), "Wishlist");
            //return "success";
        }
    }
}

1516 2.4 - IHFF/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IHFF.Models;
using IHFF.Repositories;
using IHFF.Interfaces;

namespace IHFF.Controllers
{
    public class RestaurantController : Controller
    {
        private IRestaurantRepository restaurantsRepository = new RestaurantsRepository();
        private IWishlistRepository wishlistRepository = new WishlistRepository();

        public ActionResult Index() // het resultaat van een actie(methode), laat alle restauranten zien in de view
        {
           return View(restaurantsRepository.GetAllRestaurants());
        }

        [HttpPost] // doormiddel van een httpost wordt de methode/actie alleen uitgevoerd/verwerkt/handeld met HTTP post requesten 
        public ActionResult Index(int Date, TimeSpan Time, int Amount, int RestaurantId)
        {
            Wishlist wishlist = Wishlist.Instance;

            Restaurant restaurant = restaurantsRepository.GetRestaurant(RestaurantId);
            RestaurantReservation r = restaurantsRepository.CreateReservation(restaurant, Amount, Time, Date);

            WishlistItem item = new WishlistItem(r, wishlist);

            wishlist.AddItemToWishlist(item);

            return RedirectToAction(nameof(WishlistController.Index), "Wishlist");
        }

        public ActionResult RestaurantInfo(int RestaurantId) // Het resultaat/methode/actie van het drukken op een specefiek restaurant waarbij er wordt gekeken naar de res.id en dit wordt gematched, waardoor de juiste info naar voren komt. 
        {
            return View(restaurantsRepository.GetRestaurant(RestaurantId));
        }
    }
}

1516 2.4 - IHFF/Controllers/SpecialsController.cs
using IHFF.Interfaces;
using IHFF.Models;
using IHFF.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IHFF.Controllers
{
    public class SpecialsController : Controller
    {
        private ISpecialsRepository specialsRepository = new SpecialsRepository();
        private IWishlistRepository wishlistRepository = new WishlistRepository();

        // GET: Specials
        public ActionResult Index()
        {
            return View(specialsRepository.GetAllSpecials());
        }

        [HttpPost]
        public ActionResult Index(int EventId, int ticketAmount)
        {
            Wishlist wishlist = Wishlist.Instance;
            Event e = specialsRepository.GetSpecialEvent(EventId);

            WishlistItem item = new WishlistItem(e, ticketAmount, wishlist);

            wishlist.WishlistItems.Add(item);

            Wishlist.Instance = wishlist;
            return RedirectToAction(nameof(WishlistController.Index), "Wishlist");
        }

        public ActionResult GetSpecials(int Id)
        {
            return PartialView("_SpecialView", specialsRepository.GetSpecials(Id));
        }
    }
}

1516 2.4 - IHFF/Views/Home/Index.cshtml
@using IHFF.Models
@model HomeViewModel
@{
    ViewBag.Title = "Home";
}

@Html.Partial("_Banner")
<hr />
@Html.Partial("_MovieContent", Model.Movies)
<hr />
@Html.Partial("_RestaurantContent", Model.Restaurants)
<hr />
@Html.Partial("_SpecialsContent", Model.Specials)
<hr />
@Html.Partial("_InfoContent")
<hr />

1516 2.4 - IHFF/Views/Home/ViewFilms.cshtml
@using IHFF.Models
@using IHFF.Helpers
@model IEnumerable<Movie>

@{
    ViewBag.Title = "View Films";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Director)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearOfRelease)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IMDBRating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Actors)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
    </tr>

@foreach (Movie item in Model) {
    <tr>
        <td>
            @{
                if (item.Image != null)
                {
                    <a href="@item.IMDBUrl">@Html.Image(@item.Image)</a>
                }
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Director)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YearOfRelease)
        </td>
        <td>
            <a href="@item.IMDBUrl">@Html.DisplayFor(modelItem => item.IMDBRating)</a>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Actors)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
    </tr>
}

</table>

1516 2.4 - IHFF/Views/Home/_Banner.cshtml
<div class="row myrow banner">
    <div class="col-sm-4 col-lg-3 overlay">
        <h2>
            #IHFF 2016<br />
            29 juni - 3 juli '16
        </h2>
        <p>
            Dit vijfdaagse festival, durende van woensdag tot en met zondag vindt plaats in het centrum van Haarlem.
            Samen met de restaurant ondernemers, filmzalen en andere locaties biedt dit festival een uniqe ervaringen aan.
        </p>
        <br />
        <br />
        @Html.ActionLink("Lees verder", "", null, new { @class = "btn btn-default" })
        <hr />
    </div>
    <div class="col-sm-8 col-lg-2 col-lg-offset-7 pull-down ">
        <a href="@Url.Action("Index", "Movies")" class="btn btn-primary btn-lg pull-right space-below alt-button">
            View Schedule <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
        </a>

    </div>
</div>
<div class="row row-inverse">
    <div class="col-md-6">
        <h2>
            Welkom bij het<br />
            Internationaal Haarlems Film Festival
        </h2>
        <p>
            Het IHFF bestaat al vele jaren en focused zich op films, cultuur, eten en de geweldige stad Haarlem!
        </p>
        <p>
            Dit vijfdaagse festival, durende van woensdag tot en met zondag vindt plaats in het centrum van Haarlem.
            Samen met de restaurant ondernemers, filmzalen en andere locaties maken we er een groot feest van.
        </p>
        <p>
            Het festival is ervoor om mensen kennis te laten maken met culinair, cultuur en films.
            Tevens kan op deze manier Haarlem op de kaart gezet worden!
        </p>
    </div>
    <div class="col-md-5 col-md-offset-1">
        <div class="row justify-height-container">
            <div class="thumbnail col-sm-6 justify-height">
                <img src="~/Resources/Photos/filmoverzicht.png" class="img-responsive" />
                <div class="overlayable">
                    @Html.ActionLink("Bekijk het filmoverzicht", "Index", "Movies", null, new { @class = "btn btn-primary btn-block overlay-overlayable", @style = "bottom: 10px"})
                </div>
                <p>
                    Het IHFF bied meerdere films aan dit jaar, welke spectaculaire titels ga jij bekijken?
                </p>
                <hr class="justify-height"/>
            </div>
            <div class="thumbnail col-sm-6 justify-height">
                <img src="~/Resources/Photos/specialetickets.png" class="img-responsive" />
                <div class="overlayable">
                    @Html.ActionLink("Speciale tickets", "Index", "Specials", null, new { @class = "btn btn-primary btn-block overlay-overlayable", @style = "bottom: 10px" })
                </div>
                <p>
                    Het IHFF biedt nu ook speciale tickets aan die verschillende activiteiten combineren, verdubbel de pret!
                </p>
                <hr class="pull-down"/>
            </div>
        </div>
    </div>
</div>

1516 2.4 - IHFF/Views/Home/_InfoContent.cshtml
<div class="row justify-height-container">
    <div class="col-sm-3">
        <a href="http://www.haarlemsdagblad.nl/">
            <h3>Nieuws</h3>
        </a>
        <img src="~/Resources/Placeholder.png" class="img-responsive media-object" />
        <h5 class="media-heading">#TITLE</h5>
        <h6>-subtitle-</h6>
        <p class="media-body">
            HAARLEM De populaire ijssalon Garrone in Haarlem gaat zaterdag weer open. Net op tijd voor het Bloemencorso. 
            Dat heeft de zoon van ijsmaakster Beate Garrone laten Beate Garrone (69) werd in februari getroffen door een 
            zware hersenbloeding en ligt... 
            <a href="">Lees verder</a>
        </p>
    </div>
    <div class="col-sm-6 text-right">
        <a href="http://www.haarlemmarketing.co.uk/visit-haarlem">
            <h3>Meer over Haarlem</h3>
        </a>
        <p>
            In Haarlem is van alles te doen, het gehele jaar door. Ontdek de stad die bekend staat om haar hoogwaardige culturele aanbod, 
            de grote diversiteit aan winkels, gezellige restaurants en cafés en de uitstekende ligging nabij Amsterdam, strand en zee. 
            Een stad met een rijke historie, prachtige monumenten en een Bourgondische sfeer. De ideale bestemming voor een dagtrip of 
            een weekendje weg.
        </p>
        <a class="twitter-timeline" href="https://twitter.com/hashtag/IHFF" data-widget-id="728162730910355456">#IHFF Tweets</a>
        <script>
            !function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https';
                if (!d.getElementById(id)) {
                    js = d.createElement(s);
                    js.id = id;
                    js.src = p + "://platform.twitter.com/widgets.js";
                    fjs.parentNode.insertBefore(js, fjs);
                }
            }
            (document, "script", "twitter-wjs");
        </script>
    </div>
    <div class="col-xs-0 col-sm-3 justify-height justify-height-container overlayable">
        <img src="~/Resources/Photos/GroteMarkt.jpg" class="justify-height img-responsive overlayable" />
        <div class="overlay-overlayable label-default btn-block text-center"><h2>Haarlem</h2></div>
    </div>
</div>

1516 2.4 - IHFF/Views/Home/_MovieContent.cshtml
@using IHFF.Models
@using IHFF.Helpers
@model IEnumerable<Movie>
<div class="row justify-height-container">
    <div class="col-xs-0 col-sm-3 justify-height justify-height-container overlayable">
        <img src="~/Resources/Photos/Cinema.jpg" class="justify-height img-responsive" />
        <div class="overlay-overlayable label-default btn-block text-center"><h2>Films</h2></div>
    </div>
    <div class="col-xs-12 col-sm-9">
        <a href="@Url.Action("Index", "Movies")">
            <h3>Films</h3>
        </a>
        <div class="row">
            <p class="col-sm-8">
                Het Internationaal Haarlem Film Festival draait om films en gezelligheid.
                Daarom zijn er vele films beschikbaar om gezellig met vrienden of familie naar toe te gaan.
                Er zijn vele locaties beschikbaar allen met hun eigen films en er zal altijd een film tussen zitten voor jou!
            </p>
        </div>
        <h4>
            Aanbevolen films <!-- Might need to change... -->
        </h4>
        <div class="container row-inverse">
            <hr class="dashed" />
            <div class="row recommendation">
                @foreach (Movie item in Model)
                {
                    <div class="col-sm-3 thumbnail recommendation">
                        <a href="@Url.Action("MovieInfo", "Movies", new { id = item.MovieId })" class="fancybox">
                            <img src="@String.Format( "data:image/png;base64,{0}", item.GetImage() )" class="img-responsive"/>
                        </a>
                    </div>
                }
            </div>
            <div class="row row-inverse">
                @foreach (Movie item in Model)
                {
                    <div class="col-xs-3">
                        <p class="text-center">@item.GetName().TrimStringIfLongerThan(18)</p>
                    </div>
                }                
            </div>
            <hr class="dashed" />
        </div>
    </div>
</div>

1516 2.4 - IHFF/Views/Home/_RestaurantContent.cshtml
@using IHFF.Models
@using IHFF.Helpers
@model IEnumerable<Restaurant>
<div class="row text-right justify-height-container">
    <div class="col-xs-12 col-sm-9">
        <a href="@Url.Action("Index", "Restaurant")">
            <h3>Dineren</h3>
        </a>
        <div class="row">
            <p class="col-sm-8 pull-right">
                Lekker eten voor of na een film kan ook natuurlijk!<br />
                Het culinaire centrum van Haarlem staat volledig open voor gasten die gezellig 
                willen kletsen over de films of activiteiten onder het genot van een heerlijk diner.<br />
                <br />
                Kijk welke restaurants meedoen met het festival en reserveer snel voor er geen plek meer is!
            </p>
        </div>
        <h4>
            Populaire restaurants <!-- Might need to change... -->
        </h4>
        <div class="container row-inverse">
            <div class="row recommendation">
                @foreach (Restaurant item in Model)
                {
                    <div class="col-sm-3 thumbnail recommendation">
                        <a href="@Url.Action("RestaurantInfo", "Restaurant", new { EventId = item.RestaurantId })">
                            <img src="@String.Format( "data:image/png;base64,{0}", item.Image )" class="img-responsive" />
                        </a>
                    </div>
                }
            </div>
            <div class="row row-inverse">
                @foreach (Restaurant item in Model)
                {
                    <div class="col-xs-3">
                        <p class="text-center">@item.Name.TrimStringIfLongerThan(20)</p>
                        <ul class="list-inline rating text-center">
                            @for (int i = 1; i <= 5; i++)
                            {
                                //Iterate 5 times for all the star ratings
                                //Check if iteration is lower than the rating, if so put full star
                                if (i <= (int)item.Rating)
                                {
                                    <li class="rating"><img src="~/Resources/star.png" /></li>
                                }
                                //Check if iteration is between value and value + 1 and write half star
                                else if (i > item.Rating && i < item.Rating + 1)
                                {
                                    int percentage = (int)((item.Rating % 1) * 100);
                                    string gradiant = string.Format("white {0}%, rgba(255, 255, 255, 0.3) {1}%, rgba(255, 255, 255, 0.3) 100%", percentage, percentage+1);
                                    <li class="rating" style="background: -webkit-linear-gradient(left, @gradiant ); 
                                        background: -o-linear-gradient(left, @gradiant );
                                        background: -moz-linear-gradient(left, @gradiant );
                                        background: linear-gradient(to right, @gradiant );
                                        "><img src="~/Resources/star.png" /></li>
                                }
                                //Otherwise write empty star
                                else
                                {
                                    <li class="rating norating"><img src="~/Resources/star.png" /></li>
                                }
                            }
                        </ul>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="col-xs-0 col-sm-3 justify-height justify-height-container overlayable">
        <img src="~/Resources/Photos/Dineren.jpg" class="justify-height img-responsive" />
        <div class="overlay-overlayable label-default btn-block text-center"><h2>Restaurants</h2></div>
    </div>
</div>

1516 2.4 - IHFF/Views/Home/_SpecialsContent.cshtml
@using IHFF.Models
@using IHFF.Helpers
@model IEnumerable<Special>
<div class="row justify-height-container">
    <div class="col-xs-0 col-sm-3 justify-height justify-height-container overlayable">
        <img src="~/Resources/Photos/Evenementen.jpg" class="justify-height img-responsive" />
        <div class="overlay-overlayable label-default btn-block text-center">
            <h2>Specials</h2>
        </div>
    </div>
    <div class="col-xs-12 col-sm-9">
        <a href="@Url.Action("Index", "Specials")">
            <h3>Specials/Evenementen</h3>
        </a>
        <div class="row">
            <p class="col-sm-8">
                Naast veel belovende films die het festival aanbiedt hebben wij ook verschillende activiteiten op kaart gezet voor jong tot oud. 
                Onze bezoekers met een ticket hebben toegang tot alle evenementen en activiteiten die het festival aanbiedt en is er ook een 
                parkeerplek gereserveerd voor al onze bezoekers tot 200 parkeerplaatsen (op = op!). eventueel zijn de evenementen en 
                activiteiten ook beschickbaar gesteld voor bezoekers met rolstoel of handicap.
            </p>
        </div>
        <h4>
            Highlights <!-- Might need to change... -->
        </h4>
        <div class="container row-inverse">
            <div class="row recommendation">
                @foreach (Special item in Model)
                {
                    <div class="col-sm-3 thumbnail recommendation">
                        <a href="@Url.Action("Index", "Special")" class="fancybox">
                            @if (item.Name.Contains("lezing") || item.Name.Contains("Lezing"))
                            {
                                <img src="~/Resources/lecture.jpg" class="img-responsive" />
                            }
                            else
                            {
                                <img src="~/Resources/discussion_forum.jpg" class="img-responsive" />
                            }
                        </a>
                    </div>
                }
            </div>
            <div class="row row-inverse">
                @foreach (Special item in Model)
                {
                    <div class="col-xs-3">
                        <p class="text-center">@item.Name.TrimStringIfLongerThan(18)</p>
                    </div>
                }
            </div>
        </div>
    </div>
</div>