1516 2.4 - IHFF/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IHFF.Models;
using IHFF.Repositories;
using IHFF.Interfaces;

namespace IHFF.Controllers
{
    public class MoviesController : Controller
    {
        private IMovieRepository moviesRepository = new MoviesRepository();
        private IWishlistRepository wishlistRepository = new WishlistRepository();
        private IRestaurantRepository restaurantRepository = new RestaurantsRepository();
        private IFoodFilmRepository foodFilmRepository = new FilmFoodRepository();

        public ActionResult Index()
        {
            return View(moviesRepository.GetAllUniqueMovies());
        }

        [HttpPost]
        public ActionResult Index(int EventId, int ticketAmount)
        {
            Wishlist wishlist = Wishlist.Instance;
            Event e = moviesRepository.GetMovieEvent(EventId);
            if (e == null)
            {
                return RedirectToAction(nameof(Index));
                //return "error";
            }
            WishlistItem item = new WishlistItem(e, ticketAmount, wishlist);

            wishlist.AddItemToWishlist(item);
            return RedirectToAction(nameof(WishlistController.Index), "Wishlist");
            //return "success";
        }

        public ActionResult MovieInfo(int Id)
        {
            MovieViewModel model = new MovieViewModel(restaurantRepository.GetFoodFilmRestaurants(), moviesRepository.GetMovie(Id));
            return PartialView("_MovieInfo", model);
            //return PartialView("_MovieInfo", moviesRepository.GetMovie(Id));
        }

        public ActionResult GetMovies(int day)
        {
            if(day < 0)
            {
                return PartialView("_MovieView", moviesRepository.GetAllUniqueMovies());
            }
            return PartialView("_MovieView", moviesRepository.GetMovies(day));
        }

        public ActionResult FoodAndFilm(int restaurantId, int filmId)
        {
            FoodFilmViewModel model = new FoodFilmViewModel(restaurantRepository.GetRestaurant(restaurantId), moviesRepository.GetMovie(filmId));
            return PartialView("_FoodAndFilm", model);
        }

        [HttpPost]
        public ActionResult FoodAndFilm(int EventId, int RestaurantId, TimeSpan RestaurantTime, int ticketAmount)
        {
            Wishlist wishlist = Wishlist.Instance;
            Event e = moviesRepository.GetMovieEvent(EventId);

            Restaurant restaurant = restaurantRepository.GetRestaurant(RestaurantId);
            RestaurantReservation r = restaurantRepository.CreateReservation(restaurant, ticketAmount, RestaurantTime, (int)e.Date.Day);

            FoodFilm foodFilm = new FoodFilm(e, r);

            foodFilmRepository.AddFoodFilm(foodFilm);

            WishlistItem item = new WishlistItem(foodFilm, wishlist);

            wishlist.AddItemToWishlist(item);
            return RedirectToAction(nameof(WishlistController.Index), "Wishlist");
            //return "success";
        }
    }
}

1516 2.4 - IHFF/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IHFF.Models;
using IHFF.Repositories;
using IHFF.Interfaces;

namespace IHFF.Controllers
{
    public class RestaurantController : Controller
    {
        private IRestaurantRepository restaurantsRepository = new RestaurantsRepository();
        private IWishlistRepository wishlistRepository = new WishlistRepository();

        public ActionResult Index() // het resultaat van een actie(methode), laat alle restauranten zien in de view
        {
           return View(restaurantsRepository.GetAllRestaurants());
        }

        [HttpPost] // doormiddel van een httpost wordt de methode/actie alleen uitgevoerd/verwerkt/handeld met HTTP post requesten 
        public ActionResult Index(int Date, TimeSpan Time, int Amount, int RestaurantId)
        {
            Wishlist wishlist = Wishlist.Instance;

            Restaurant restaurant = restaurantsRepository.GetRestaurant(RestaurantId);
            RestaurantReservation r = restaurantsRepository.CreateReservation(restaurant, Amount, Time, Date);

            WishlistItem item = new WishlistItem(r, wishlist);

            wishlist.AddItemToWishlist(item);

            return RedirectToAction(nameof(WishlistController.Index), "Wishlist");
        }

        public ActionResult RestaurantInfo(int RestaurantId) // Het resultaat/methode/actie van het drukken op een specefiek restaurant waarbij er wordt gekeken naar de res.id en dit wordt gematched, waardoor de juiste info naar voren komt. 
        {
            return View(restaurantsRepository.GetRestaurant(RestaurantId));
        }
    }
}

1516 2.4 - IHFF/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IHFF.Repositories;
using IHFF.Interfaces;
using IHFF.Models;

namespace IHFF.Controllers
{
    public class SharedController : Controller
    {
        IWishlistRepository wishlistRepository = new WishlistRepository();

        public ActionResult ShowMiniWishlist()
        {
            return PartialView("_WishlistMini", Wishlist.Instance);
        }
    }
}

1516 2.4 - IHFF/Views/Shared/_Footer.cshtml
<footer class="navbar navbar-inverse">
    <div class="container">
        <div class="row">
            <div class="col-xs-4">
                <!-- BRAND HERE -->
                    <img src="~/Resources/Brand.png" class="brand" />
            </div>
            <div class="col-xs-4">
                <h3>Nieuwsbrief</h3>
                <p>
                    Blijf op de hoogte van nieuwe ontwikkelingen of acties en schrijf je in voor de nieuwsbrief
                </p>
            </div>
            <div class="col-xs-4">
                <h3 class="white">Contact</h3>
                <div class="row">
                    <div class="col-xs-3">Telefoon:</div>
                    <div class="col-xs-9">+31 (0) 555 555 5555</div>
                </div>
                <div class="row">
                    <div class="col-xs-3">E-mail:</div>
                    <div class="col-xs-9">info@ihff.com</div>
                </div>
                <div class="row">
                    <div class="col-xs-3">Twitter:</div>
                    <div class="col-xs-9">@@IHFF</div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-xs-4">
                <!-- LANGUAGE ICONS HERE -->
                #PLACEHOLDER LANGUAGE
            </div>
            <div class="col-xs-4">
                <!-- NEWSLETTER INPUT HERE -->
                    <div class="input-group">
                        <input class="form-control"
                               data-val="true"
                               data-val-regex="Vul aub een valide email in. voorbeeld: voorbeeld@email.nl"
                               data-val-regex-pattern="^[A-z0-9]+@@(?:[A-z0-9]+\.)+[A-z]+$"
                               data-val-required="The Email field is required."
                               id="Email"
                               name="Email"
                               placeholder="voorbeeld@domein.nl"
                               type="text"
                               value="">
                        <div class="input-group-btn">
                            <button class="btn btn-primary">Schrijf in</button>
                        </div>
                    </div>                
            </div>
            <div class="col-xs-4">
                <!-- SOCIAL MEDIA ICONS HERE -->
                <div class="row sm-icons small">
                    <div class="col-xs-3">
                        <img src="~/Resources/Icons/facebook.png" class="img-responsive" />
                    </div>
                    <div class="col-xs-3">
                        <img src="~/Resources/Icons/twitter.png" class="img-responsive" />
                    </div>
                    <div class="col-xs-3">
                        <img src="~/Resources/Icons/google-plus.png" class="img-responsive" />
                    </div>
                    <div class="col-xs-3">
                        <img src="~/Resources/Icons/note.png" class="img-responsive" style="background-color:#0B66AD; padding:5px;" />
                    </div>
                </div>
            </div>
        </div>
        <br />
    </div>
    <div class="row">
        <div class="container">
            <div class="col-xs-6">
                <p class="copyright">&copy; copyright @DateTime.Now.Year CMD. All rights reserved. </p>
            </div>
            <div class="col-xs-6">
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Films", "Index", "Movies")</li>
                        <li>@Html.ActionLink("Restaurants", "Index", "Restaurant")</li>
                        <li>@Html.ActionLink("Specials", "Index", "Specials")</li>
                        <li>@Html.ActionLink("FAQ", "Index", "FAQ")</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

1516 2.4 - IHFF/Views/Shared/_Header.cshtml
<script>
    $(document).ready(function () {
            $(".menu").click(function () {
                $(".menu").each(function () {
                    $(this).removeClass("active");
                });
                $(this).addClass('active');
            });
        });
</script>

<header class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <div class="row">
                <div class="col-xs-12 col-sm-8 col-md-10">
                    <a href="@Url.Action("Index", "Home")">
                        <img src="~/Resources/Brand.png" class="img-responsive"/>
                    </a>
                </div>
                <div class="col-xs-8 col-sm-4 col-md-2 pull-right">
                    <a href="@Url.Action("ShowMiniWishlist", "Shared")" 
                       class="btn btn-primary btn-lg btn-block pull-right fancybox">
                        My Wishlist
                    </a>
                    <!--Html.ActionLink("My Wishlist", "ShowMiniWishlist", "Shared", null, new { class = "btn btn-primary btn-lg btn-block pull-right fancybox" })-->
                </div>

            </div>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
    </div>
    <div class="row">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", null, new { @class = "menu active"})</li>
                    <li>@Html.ActionLink("Films", "Index", "Movies", null, new { @class = "menu" })</li>
                    <li>@Html.ActionLink("Restaurants", "Index", "Restaurant", null, new { @class = "menu" })</li>
                    <li>@Html.ActionLink("Specials", "Index", "Specials", null, new { @class = "menu" })</li>
                    <li>@Html.ActionLink("FAQ", "Index", "FAQ", null, new { @class = "menu" })</li>
                </ul>
            </div>
        </div>
    </div>
</header>

<script>
    $(document).ready(function () {
        $(".fancybox").click(function () {
            $.fancybox.open({
                content: $('<div>').load($(this).attr('href')),
                type: 'ajax',
                maxWidth: 800,
                fitToView: false,
                autoSize: true,
                openEffect: 'fade',
                closeEffect: 'fade',
            });
            return false;
        })

        /*$(".sendBtn").click(function (e) {
            e.preventDefault();

            var form = $(this).closest('form');

            $.ajax({
                url: form.attr('action'),
                type: "POST",
                data: form.serialize(),
                success: function (result) {
                    if (result == "success") {
                        jQuery.fancybox.close();
                        // mini wishlist openen
                        $.fancybox.open({
                            content: $('<div>').load("/Shared/ShowMiniWishlist"),
                            type: 'ajax',
                            maxWidth: 800,
                            fitToView: false,
                            autoSize: true,
                            openEffect: 'fade',
                            closeEffect: 'fade',
                            AutoDimension: true,
                        });
                    }
                    else {
                        $.fancybox.open({
                            content: $('<div><p style="color:red">Er is iets mis gegaan.</p></div>'),
                            type: 'ajax',
                            maxWidth: 800,
                            fitToView: false,
                            autoSize: true,
                            openEffect: 'fade',
                            closeEffect: 'fade',
                            AutoDimension: true,
                        });
                    }
                }
            });
        }); Busy with it, but I didn't got it working yet /Susanne  */ 
    });
</script>

1516 2.4 - IHFF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IHFF</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")



    <script src="~/Scripts/jquery.fancybox-buttons.js"></script>
    <script src="~/Scripts/jquery.fancybox-media.js"></script>
    <script src="~/Scripts/jquery.fancybox-thumbs.js"></script>
    <script src="~/Scripts/jquery.fancybox.js"></script>
    <script src="~/Scripts/jquery.fancybox.pack.js"></script>
    <script src="~/Scripts/jquery.mousewheel-3.0.6.pack.js"></script>

    
    <link href="~/Content/jquery.fancybox.css" rel="stylesheet" />
    <link href="~/Content/jquery.fancybox-buttons.css" rel="stylesheet" />
    <link href="~/Content/jquery.fancybox-thumbs.css" rel="stylesheet" />
</head>
<body>
    @Html.Partial("_Header")
    <div class="container body-content">
        @RenderBody()
    </div>
    @Html.Partial("_Footer")
    @RenderSection("scripts", required: false)
</body>
</html>

1516 2.4 - IHFF/Views/Shared/_WishlistMini.cshtml
@using IHFF.Models
@using IHFF.Helpers
@model Wishlist
<div class="row row-inverse miniWishlistTitle">
    <h3>Wishlist</h3>
    <p>
        Kijk hier voor het filmoverzicht,
        bekijk het restaurantaanbod
        of koop een combi-ticket!
    </p>
</div>
<div class="container">

    @{ if (Model.WishlistItems.Count == 0)
        {
            <p>
                <b>
                    <i>
                        U heeft nog niets in uw wishlist staan. Kijk bij
                        @Html.ActionLink("Movies", "Index", "Movies")
                        of
                        @Html.ActionLink("Specials", "Index", "Specials")
                        om iets toe te voegen.
                    </i>
                </b>
            </p>
        }
        else
        {
            <table class="wishlistMini">
                <thead>
                    <tr>
                        <td class="col-md-3"><b>Activiteit</b></td>
                        <td class="col-md-4"><b>Dag &amp; tijd</b></td>
                        <td class="col-md-3"><b>Locatie</b></td>
                        <td class="col-md-2"><b>Aantal</b></td>
                        <td class="col-md-1"><b>Prijs</b></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (WishlistItem item in Model.WishlistItems.Where(x => !x.PayedFor))
                    {
                        <tr>
                            <td>@item.GetName()</td>
                            <td>@Globals.CurrentCulture.DateTimeFormat.GetDayName(item.Date.DayOfWeek).UppercaseFirst(), @item.Date.ToString("HH:mm") uur</td>
                            <td>@item.GetLocation()</td>
                            <td>@item.Amount</td>
                            <td>&euro;@item.GetPrice()</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    }
    <div class="row">
        <div class="col-md-4 col-md-offset-8">
            @Html.ActionLink("Naar wishlist/betalen", "Index", "Wishlist", null, new { @class = "btn btn-primary btn-block pull-down" })
        </div>
    </div>
</div>